# Generated by Django 4.1.7 on 2023-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_match_away_team_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.IntegerField(default=0),
        ),
    ]
