# Generated by Django 4.1.7 on 2023-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_draws_team_goals_lost_team_goals_scored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='promoted_teams',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='relegated_teams',
            field=models.IntegerField(default=1),
        ),
    ]
