# Generated by Django 4.1.7 on 2023-04-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_league_promoted_teams_league_relegated_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='asists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchid', to='main.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerid', to='main.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamid', to='main.team')),
            ],
        ),
    ]
