# Generated by Django 4.1.7 on 2023-04-01 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_player_asists_player_goals_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='scores',
            name='goals',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_result',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_result',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
